language: crystal
crystal:
    - latest

sudo: required

notifications:
    email:
        - jayrad.security@protonmail.com

branches:
    only:
        - master

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libyaml-dev

script:
    - make test
