#!/bin/sh

KEMAL_ENV=test crystal spec

echo "\r\n+---------------------+"
echo "|  Analyzing -> style |"
echo "+---------------------+"
./tests/analyze-style

echo "\r\n+----------------------+"
echo "|  Analyzing -> syntax |"
echo "+----------------------+"
./tests/analyze-syntax

echo "\r\n+--------------------+"
echo "|  Analyzing -> all  |"
echo "+--------------------+"
./tests/analyze-all

echo "+--------------------+"
echo "|  All Done          |"
echo "+--------------------+"
